// Mocks generated by Mockito 5.4.4 from annotations
// in test_task/test/repository/news_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_task/data/response_models/news_response.dart' as _i2;
import 'package:test_task/data/services/news_rest_client/news_rest_client.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNewsResponse_0 extends _i1.SmartFake implements _i2.NewsResponse {
  _FakeNewsResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NewsRestClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsRestClient extends _i1.Mock implements _i3.NewsRestClient {
  @override
  _i4.Future<_i2.NewsResponse> fetchNews() => (super.noSuchMethod(
        Invocation.method(
          #fetchNews,
          [],
        ),
        returnValue: _i4.Future<_i2.NewsResponse>.value(_FakeNewsResponse_0(
          this,
          Invocation.method(
            #fetchNews,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.NewsResponse>.value(_FakeNewsResponse_0(
          this,
          Invocation.method(
            #fetchNews,
            [],
          ),
        )),
      ) as _i4.Future<_i2.NewsResponse>);
}
